version: '3.7'

services:
  postgres:
    image: postgres:12
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=qwerty
    ports:
      - "5433:5432"
  web:
    depends_on:
      - postgres
    image: platform
    volumes:
      - /home/sergei:/deploy/tomcat/logs
    ports:
      - "8081:8081"
    command: sh -c " apt update && apt install -y ffmpeg && ./gradlew updateDb && ./deploy/tomcat/bin/startup.sh && tail -f /dev/null"
