-- begin PLATFORM_CAMERA
alter table PLATFORM_CAMERA add constraint FK_PLATFORM_CAMERA_ON_USER foreign key (USER_ID) references SEC_USER(ID)^
create index IDX_PLATFORM_CAMERA_ON_USER on PLATFORM_CAMERA (USER_ID)^
-- end PLATFORM_CAMERA
-- begin PLATFORM_NODE
alter table PLATFORM_NODE add constraint FK_PLATFORM_NODE_ON_USER foreign key (USER_ID) references SEC_USER(ID)^
create index IDX_PLATFORM_NODE_ON_USER on PLATFORM_NODE (USER_ID)^
-- end PLATFORM_NODE
-- begin PLATFORM_VIDEO
alter table PLATFORM_VIDEO add constraint FK_PLATFORM_VIDEO_ON_FILEDESCRIPTORID foreign key (FILEDESCRIPTORID) references SYS_FILE(ID)^
alter table PLATFORM_VIDEO add constraint FK_PLATFORM_VIDEO_ON_CAMERAID foreign key (CAMERAID) references PLATFORM_CAMERA(ID)^
alter table PLATFORM_VIDEO add constraint FK_PLATFORM_VIDEO_ON_PARENTVIDEO foreign key (PARENTVIDEO) references PLATFORM_VIDEO(ID)^
create index IDX_PLATFORM_VIDEO_ON_FILEDESCRIPTORID on PLATFORM_VIDEO (FILEDESCRIPTORID)^
create index IDX_PLATFORM_VIDEO_ON_CAMERAID on PLATFORM_VIDEO (CAMERAID)^
create index IDX_PLATFORM_VIDEO_ON_PARENTVIDEO on PLATFORM_VIDEO (PARENTVIDEO)^
-- end PLATFORM_VIDEO
