-- begin PLATFORM_CAMERA
alter table PLATFORM_CAMERA add constraint FK_PLATFORM_CAMERA_ON_USER foreign key (USER_ID) references SEC_USER(ID)^
create index IDX_PLATFORM_CAMERA_ON_USER on PLATFORM_CAMERA (USER_ID)^
-- end PLATFORM_CAMERA
-- begin PLATFORM_VIDEO
alter table PLATFORM_VIDEO add constraint FK_PLATFORM_VIDEO_ON_FILEDESCRIPTORID foreign key (FILEDESCRIPTORID) references SYS_FILE(ID)^
alter table PLATFORM_VIDEO add constraint FK_PLATFORM_VIDEO_ON_CAMERAID foreign key (CAMERAID) references PLATFORM_CAMERA(ID)^
alter table PLATFORM_VIDEO add constraint FK_PLATFORM_VIDEO_ON_PARENTVIDEO foreign key (PARENTVIDEO) references PLATFORM_VIDEO(ID)^
alter table PLATFORM_VIDEO add constraint FK_PLATFORM_VIDEO_ON_VIDEOPROCESSINGID foreign key (VIDEOPROCESSINGID) references PLATFORM_VIDEO_PROCESSING(ID)^
create index IDX_PLATFORM_VIDEO_ON_FILEDESCRIPTORID on PLATFORM_VIDEO (FILEDESCRIPTORID)^
create index IDX_PLATFORM_VIDEO_ON_CAMERAID on PLATFORM_VIDEO (CAMERAID)^
create index IDX_PLATFORM_VIDEO_ON_PARENTVIDEO on PLATFORM_VIDEO (PARENTVIDEO)^
create index IDX_PLATFORM_VIDEO_ON_VIDEOPROCESSINGID on PLATFORM_VIDEO (VIDEOPROCESSINGID)^
-- end PLATFORM_VIDEO
-- begin PLATFORM_NODE
alter table PLATFORM_NODE add constraint FK_PLATFORM_NODE_ON_USER foreign key (USER_ID) references SEC_USER(ID)^
create index IDX_PLATFORM_NODE_ON_USER on PLATFORM_NODE (USER_ID)^
-- end PLATFORM_NODE
-- begin PLATFORM_IMAGE
alter table PLATFORM_IMAGE add constraint FK_PLATFORM_IMAGE_ON_FILEDESCRIPTORID foreign key (FILEDESCRIPTORID) references SYS_FILE(ID)^
alter table PLATFORM_IMAGE add constraint FK_PLATFORM_IMAGE_ON_PARENTVIDEOID foreign key (PARENTVIDEOID) references PLATFORM_VIDEO(ID)^
alter table PLATFORM_IMAGE add constraint FK_PLATFORM_IMAGE_ON_IMAGEPROCESSINGID foreign key (IMAGEPROCESSINGID) references PLATFORM_IMAGE_PROCESSING(ID)^
create index IDX_PLATFORM_IMAGE_ON_FILEDESCRIPTORID on PLATFORM_IMAGE (FILEDESCRIPTORID)^
create index IDX_PLATFORM_IMAGE_ON_PARENTVIDEOID on PLATFORM_IMAGE (PARENTVIDEOID)^
create index IDX_PLATFORM_IMAGE_ON_IMAGEPROCESSINGID on PLATFORM_IMAGE (IMAGEPROCESSINGID)^
-- end PLATFORM_IMAGE
-- begin PLATFORM_IMAGE_PROCESSING
alter table PLATFORM_IMAGE_PROCESSING add constraint FK_PLATFORM_IMAGE_PROCESSING_ON_NODEID foreign key (NODEID) references PLATFORM_NODE(ID)^
create index IDX_PLATFORM_IMAGE_PROCESSING_ON_NODEID on PLATFORM_IMAGE_PROCESSING (NODEID)^
-- end PLATFORM_IMAGE_PROCESSING
-- begin PLATFORM_VIDEO_PROCESSING
alter table PLATFORM_VIDEO_PROCESSING add constraint FK_PLATFORM_VIDEO_PROCESSING_ON_NODEID foreign key (NODEID) references PLATFORM_NODE(ID)^
create index IDX_PLATFORM_VIDEO_PROCESSING_ON_NODEID on PLATFORM_VIDEO_PROCESSING (NODEID)^
-- end PLATFORM_VIDEO_PROCESSING
