alter table PLATFORM_VIDEO add constraint FK_PLATFORM_VIDEO_ON_CAMERAID foreign key (CAMERAID) references PLATFORM_CAMERA(ID);
create index IDX_PLATFORM_VIDEO_ON_ID on PLATFORM_VIDEO (ID);
create index IDX_PLATFORM_VIDEO_ON_CAMERAID on PLATFORM_VIDEO (CAMERAID);
