alter table PLATFORM_VIDEO add constraint FK_PLATFORM_VIDEO_ON_FILEDESCRIPTORID foreign key (FILEDESCRIPTORID) references SYS_FILE(ID);
create index IDX_PLATFORM_VIDEO_ON_FILEDESCRIPTORID on PLATFORM_VIDEO (FILEDESCRIPTORID);
