alter table PLATFORM_VIDEO add constraint FK_PLATFORM_VIDEO_ON_VIDEOPROCESSINGID foreign key (VIDEOPROCESSINGID) references PLATFORM_VIDEO_PROCESSING(ID);
create index IDX_PLATFORM_VIDEO_ON_VIDEOPROCESSINGID on PLATFORM_VIDEO (VIDEOPROCESSINGID);
