alter table PLATFORM_VIDEO_PROCESSING add constraint FK_PLATFORM_VIDEO_PROCESSING_ON_NODEID foreign key (NODEID) references PLATFORM_NODE(ID);
alter table PLATFORM_VIDEO_PROCESSING add constraint FK_PLATFORM_VIDEO_PROCESSING_ON_VIDEOID foreign key (VIDEOID) references PLATFORM_VIDEO(ID);
create index IDX_PLATFORM_VIDEO_PROCESSING_ON_NODEID on PLATFORM_VIDEO_PROCESSING (NODEID);
create index IDX_PLATFORM_VIDEO_PROCESSING_ON_VIDEOID on PLATFORM_VIDEO_PROCESSING (VIDEOID);
