alter table PLATFORM_IMAGE_PROCESSING add constraint FK_PLATFORM_IMAGE_PROCESSING_ON_NODEID foreign key (NODEID) references PLATFORM_NODE(ID);
create index IDX_PLATFORM_IMAGE_PROCESSING_ON_NODEID on PLATFORM_IMAGE_PROCESSING (NODEID);
