alter table PLATFORM_IMAGE add constraint FK_PLATFORM_IMAGE_ON_FILEDESCRIPTORID foreign key (FILEDESCRIPTORID) references SYS_FILE(ID);
alter table PLATFORM_IMAGE add constraint FK_PLATFORM_IMAGE_ON_PARENTVIDEOID foreign key (PARENTVIDEOID) references PLATFORM_VIDEO(ID);
alter table PLATFORM_IMAGE add constraint FK_PLATFORM_IMAGE_ON_IMAGEPROCESSINGID foreign key (IMAGEPROCESSINGID) references PLATFORM_IMAGE_PROCESSING(ID);
create index IDX_PLATFORM_IMAGE_ON_FILEDESCRIPTORID on PLATFORM_IMAGE (FILEDESCRIPTORID);
create index IDX_PLATFORM_IMAGE_ON_PARENTVIDEOID on PLATFORM_IMAGE (PARENTVIDEOID);
create index IDX_PLATFORM_IMAGE_ON_IMAGEPROCESSINGID on PLATFORM_IMAGE (IMAGEPROCESSINGID);
